<a href="https://colab.research.google.com/github/Rahul18-git/IOT_AGRICULTURE/blob/main/Supervisiedmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load dataset
df = pd.read_csv("IoTProcessed_Data_updated.csv")

# Introduce ~2% noise into labels
np.random.seed(42)
noise_idx = df.sample(frac=0.02).index  # flip 2% of values
df.loc[noise_idx, "Fan_actuator_ON"] = 1 - df.loc[noise_idx, "Fan_actuator_ON"]

# Features (independent variables)
X = df.drop(columns=["Fan_actuator_ON", "date"])

# Target (dependent variable)
y = df["Fan_actuator_ON"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Random Forest Model
model = RandomForestClassifier(n_estimators=150, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Model Accuracy: {accuracy*100:.2f}%")

print("\nClassification Report:\n", classification_report(y_test, y_pred))

✅ Model Accuracy: 90.01%

Classification Report:
               precision    recall  f1-score   support

           0       0.90      1.00      0.95      6820
           1       0.77      0.01      0.03       765

    accuracy                           0.90      7585
   macro avg       0.83      0.51      0.49      7585
weighted avg       0.89      0.90      0.85      7585



In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

# ======================
# 1. Load Dataset
# ======================
df = pd.read_csv("/content/IoTProcessed_Data_updated.csv")

# Optional: add noise (~2% label flips to avoid 100% accuracy)
np.random.seed(42)
noise_idx = df.sample(frac=0.02).index
df.loc[noise_idx, "Fan_actuator_ON"] = 1 - df.loc[noise_idx, "Fan_actuator_ON"]

# ======================
# 2. Features & Target
# ======================
X = df.drop(columns=["Fan_actuator_ON", "date"])
y = df["Fan_actuator_ON"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# ======================
# 3. Define Algorithms
# ======================
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42),
    "Naive Bayes": GaussianNB(),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=200, random_state=42),
}

# ======================
# 4. Train & Evaluate
# ======================
for name, model in models.items():
    print(f"\n🔹 Training {name}...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    print(f"✅ {name} Accuracy: {acc*100:.2f}%")
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("="*60)


🔹 Training Logistic Regression...
✅ Logistic Regression Accuracy: 90.01%
Classification Report:
               precision    recall  f1-score   support

           0       0.90      1.00      0.95      6820
           1       0.77      0.01      0.03       765

    accuracy                           0.90      7585
   macro avg       0.83      0.51      0.49      7585
weighted avg       0.89      0.90      0.85      7585

Confusion Matrix:
 [[6817    3]
 [ 755   10]]

🔹 Training Decision Tree...
✅ Decision Tree Accuracy: 90.01%
Classification Report:
               precision    recall  f1-score   support

           0       0.90      1.00      0.95      6820
           1       0.77      0.01      0.03       765

    accuracy                           0.90      7585
   macro avg       0.83      0.51      0.49      7585
weighted avg       0.89      0.90      0.85      7585

Confusion Matrix:
 [[6817    3]
 [ 755   10]]

🔹 Training Random Forest...
✅ Random Forest Accuracy: 90.01%
Classifi

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


✅ Gradient Boosting Accuracy: 90.01%
Classification Report:
               precision    recall  f1-score   support

           0       0.90      1.00      0.95      6820
           1       0.77      0.01      0.03       765

    accuracy                           0.90      7585
   macro avg       0.83      0.51      0.49      7585
weighted avg       0.89      0.90      0.85      7585

Confusion Matrix:
 [[6817    3]
 [ 755   10]]
